version: 1
validation: sovereign
default_denom: utopstar
accounts: 
- name: alice
  coins:
  - 20000umytoken
  - 200000000utopstar
- name: bob
  coins:
  - 10000umytoken
  - 100000000utopstar
client:
  openapi:
    path: docs/static/openapi.json
faucet:
  name: bob
  coins:
  - 5umytoken
  - 100000utopstar
validators:
- name: alice
  bonded: 100000000utopstar
- name: validator1
  bonded: 200000000utopstar
- name: validator2
  bonded: 100000000utopstar